/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'antoniomaria' at '4/10/16 4:57 PM' with Gradle 2.9
 *
 * @author antoniomaria, @date 4/10/16 4:57 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
