/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'antoniomaria' at '4/10/16 4:57 PM' with Gradle 2.9
 *
 * @author antoniomaria, @date 4/10/16 4:57 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
